### ISSUE TITLE
 I get the following error when I run train.py, "AttributeError: 'NoneType' object has no attribute 'decode'"

### ISSUE THREAD

**Issue by udemegane** [rosinality/stylegan2-pytorch#127]
Hello. As the title suggests, I got the following error:

`
Traceback (most recent call last):
  File "train.py", line 448, in <module>
    dataset = MultiResolutionDataset(args.path, transform, args.size)
  File "/home/udemegane/scripts/stylegan2-pytorch/dataset.py", line 23, in __init__
    self.length = int(txn.get('length'.encode('utf-8')).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/bin/python', '-u', 'train.py', '--local_rank=0', '/home/udemegane/dataset/GIA_lmdb']' returned non-zero exit status 1.
`

This is my environment.
Driver Version: 450.66       CUDA Version: 11.0
`
Package         Version  
--------------- ---------
certifi         2020.6.20
chardet         3.0.4    
cycler          0.10.0   
future          0.18.2   
idna            2.10     
joblib          0.17.0   
kiwisolver      1.2.0    
lmdb            1.0.0    
matplotlib      3.3.2    
numpy           1.19.2   
opencv-python   4.4.0.44 
pandas          1.1.2    
Pillow          7.2.0    
pip             20.0.2   
pkg-resources   0.0.0    
pyparsing       2.4.7    
python-dateutil 2.8.1    
pytz            2020.1   
requests        2.24.0   
scikit-learn    0.23.2   
scipy           1.5.2    
seaborn         0.11.0   
setuptools      44.0.0   
six             1.15.0   
threadpoolctl   2.1.0    
torch           1.6.0    
torchvision     0.7.0    
tqdm            4.50.0   
urllib3         1.25.10 
`
Thank you.

**Comment by udemegane** [comment]
I opened two of the same issues due to a browser error. Therefore, I will close this issue.
