### ISSUE TITLE
 I get the following error: AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by udemegane** [rosinality/stylegan2-pytorch#128]
Hello. As the title suggests, I got the following error:
I spent a few hours, but I can't train it.
```
Traceback (most recent call last):
  File "train.py", line 448, in <module>
    dataset = MultiResolutionDataset(args.path, transform, args.size)
  File "/home/udemegane/scripts/stylegan2-pytorch/dataset.py", line 23, in __init__
    self.length = int(txn.get('length'.encode('utf-8')).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/lib/python3.8/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/lib/python3.8/site-packages/torch/distributed/launch.py", line 256, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/udemegane/scripts/stylegan2-pytorch/venv38sg2/bin/python', '-u', 'train.py', '--local_rank=0', '/home/udemegane/dataset/GIA_lmdb']' returned non-zero exit status 1.
```

This is my environment.
Driver Version: 450.66       CUDA Version: 11.0
```
Package         Version  
--------------- ---------
certifi         2020.6.20
chardet         3.0.4    
cycler          0.10.0   
future          0.18.2   
idna            2.10     
joblib          0.17.0   
kiwisolver      1.2.0    
lmdb            1.0.0    
matplotlib      3.3.2    
numpy           1.19.2   
opencv-python   4.4.0.44 
pandas          1.1.2    
Pillow          7.2.0    
pip             20.0.2   
pkg-resources   0.0.0    
pyparsing       2.4.7    
python-dateutil 2.8.1    
pytz            2020.1   
requests        2.24.0   
scikit-learn    0.23.2   
scipy           1.5.2    
seaborn         0.11.0   
setuptools      44.0.0   
six             1.15.0   
threadpoolctl   2.1.0    
torch           1.6.0    
torchvision     0.7.0    
tqdm            4.50.0   
urllib3         1.25.10 
```
Thank you.

**Comment by udemegane** [comment]
I found that the dataset was not created successfully.
prepare.py always crashes. What can I do to solve this?
```
Make dataset of image sizes: 128, 256, 512, 1024
63253it [25:15, 13.47s/it]zsh: killed     python3 prepare_data.py --out ~/dataset/GIA_lmdb ~/dataset/GIA/
Process ForkPoolWorker-6:
Process ForkPoolWorker-7:                                                                                                                                                                                            
Process ForkPoolWorker-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)

....
```

**Comment by rosinality** [comment]
Sometime it happens when shared memory is not enough. You can may try to reduce `--n_worker` arguments.

**Comment by udemegane** [comment]
Setting n_worker to 1 seems to solve the problem.
However, even if n_worker is 1, this error may occur in rare cases.
In most cases this is not an issue so I will close this issue. Thank you
