### ISSUE TITLE
Add support for weight support of official stylegan2-ada

### ISSUE THREAD

**Issue by SystemErrorWang** [rosinality/stylegan2-pytorch#132]
Hello resinality, thank you for your implementation, it helped me a lot.
Current Nvidia released the official implementation of stylegan2-ada(https://github.com/NVlabs/stylegan2-ada), but when I was trying to convert the weight trained by this repo, I got the following error:
```
Traceback (most recent call last):
  File "convert_weight.py", line 220, in <module>
    generator, discriminator, g_ema = pickle.load(f)
  File "/mnt/wfs/mmcommwfssz/project_mm-base-vision/secretwang/stylegan2_weight_convert/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/mnt/wfs/mmcommwfssz/project_mm-base-vision/secretwang/stylegan2_weight_convert/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 439, in G_synthesis
  File "<string>", line 392, in layer
  File "<string>", line 105, in modulated_conv2d_layer
  File "<string>", line 50, in apply_bias_act
TypeError: fused_bias_act() got an unexpected keyword argument 'clamp'
```

I would like to know if you would add support for converting the weight for the official implementation, thank you!

**Comment by rosinality** [comment]
I would have to look at this, but it seems like that it is the error related to official implementation.

**Comment by SystemErrorWang** [comment]
Thank you for you quick reply, I will try to modify the code myself, thouch training script of the official repo works fine with me.

**Comment by rosinality** [comment]
Does model structure or variable naming is different from the original stylegan2? I thought it will be similiar or same.

**Comment by SystemErrorWang** [comment]
@rosinality it seems to be the environment problem, I can convert the aboved mentioned model in another mechine with my modified codes. Thank you for you kind help!
