### ISSUE TITLE
When I use your pre-trained model 550000.pt, the following error occurs

### ISSUE THREAD

**Issue by AEP-WYK** [rosinality/stylegan2-pytorch#176]
When I execute the command : python generate.py --size 256 --ckpt ./checkpoint/550000.pt

Traceback (most recent call last):
  File "generate.py", line 76, in <module>
    g_ema.load_state_dict(checkpoint["g_ema"])
  File "/home/sd02/anaconda3/envs/pytorch_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "noises.noise_0", "noises.noise_1", "noises.noise_2", "noises.noise_3", "noises.noise_4", "noises.noise_5", "noises.noise_6", "noises.noise_7", "noises.noise_8", "noises.noise_9", "noises.noise_10", "noises.noise_11", "noises.noise_12".

**Comment by rosinality** [comment]
Please replace `g_ema.load_state_dict(checkpoint["g_ema"])` with `g_ema.load_state_dict(checkpoint["g_ema"], strict=False)`
