### ISSUE TITLE
ImportError: DLL load failed while importing fused: The specified module could not be found.

### ISSUE THREAD

**Issue by erinbeesley** [rosinality/stylegan2-pytorch#177]
full error: `Traceback (most recent call last):
  File "C:\Users\mason\Desktop\midi\stylegan2-pytorch\generate.py", line 5, in <module>
    from model import Generator
  File "C:\Users\mason\Desktop\midi\stylegan2-pytorch\model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\mason\Desktop\midi\stylegan2-pytorch\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\mason\Desktop\midi\stylegan2-pytorch\op\fused_act.py", line 11, in <module>
    fused = load(
  File "C:\Users\mason\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py", line 963, in load
    return _jit_compile(
  File "C:\Users\mason\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py", line 1190, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py", line 1538, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python38\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python38\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing fused: The specified module could not be found.`

i am on Windows 10, torch version 1.7.1, i have tried CUDA 10, and CUDA 10.1
fused compiles fine, but it just can't find it at all

**Comment by erinbeesley** [comment]
solved, because i was doing 
"generate.py"
rather than
"python generate.py"
in the command line

**Comment by funParadox** [comment]
I have the same problem.
But I use "python generate.py" .
still have the same problem

**Comment by dummyuser-123** [comment]
Hi! I am also getting the same error as follows:

Traceback (most recent call last):
  File "D:\GAN\stylegan2-pytorch\convert_weight.py", line 11, in <module>
    from model import Generator, Discriminator
  File "D:\GAN\stylegan2-pytorch\model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d, conv2d_gradfix
  File "D:\GAN\stylegan2-pytorch\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "D:\GAN\stylegan2-pytorch\op\fused_act.py", line 11, in <module>
    fused = load(
  File "D:\GAN\stylegan2-pytorch\env\lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
  File "D:\GAN\stylegan2-pytorch\env\lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\GAN\stylegan2-pytorch\env\lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed while importing fused: The specified module could not be found.


Actually I was converting the weights using convert.py, so during that time I am getting this error.

**My environment has following libraries:**
certifi==2022.12.7
charset-normalizer==2.1.1
colorama==0.4.6
filelock==3.9.0
fsspec==2023.4.0
idna==3.4
Jinja2==3.1.2
lmdb==1.4.1
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.0
ninja==1.11.1.1
numpy==1.24.1
Pillow==9.3.0
requests==2.28.1
sympy==1.12
torch==2.1.1+cu118
torchaudio==2.1.1+cu118
torchvision==0.16.1+cu118
tqdm==4.66.1
typing_extensions==4.8.0
urllib3==1.26.13

Also, I was able to create dataset using given command in the readme file but when I am running other commands then I am getting this error.

@erinbeesley @funParadox @rosinality So, Do you know how to solve this error ?

**Comment by Zhouwudexiazhou** [comment]
i have the same problem ，do you solve the problem？@dummyuser-123
