### ISSUE TITLE
Shape mismatch from checkpoint with labels

### ISSUE THREAD

**Issue by mcartagenah** [rosinality/stylegan2-pytorch#191]
Hi, I'm getting this error:

```Traceback (most recent call last):
  File "/content/stylegan2-pytorch/convert_weight.py", line 248, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size, n_mlp)
  File "/content/stylegan2-pytorch/convert_weight.py", line 144, in fill_statedict
    update(state_dict, convert_dense(vars, f"G_mapping/Dense{i}", f"style.{i + 1}"))
  File "/content/stylegan2-pytorch/convert_weight.py", line 101, in update
    raise ValueError(f"Shape mismatch: {v.shape} vs {state_dict[k].shape}")
ValueError: Shape mismatch: torch.Size([512, 1024]) vs torch.Size([512, 512])```

With a checkpoint of images with shape 128x128 and with labels

**Comment by rosinality** [comment]
Currently this implement does not support to use labels.
