### ISSUE TITLE
assert state["version"] in [2, 3]

### ISSUE THREAD

**Issue by Lvhhhh** [rosinality/stylegan2-pytorch#200]
when i run convert_weight.py  --repo /media/31_sdf/stylegan2/ /media/31_sdf/stylegan2/pretrained_models/stylegan2-ffhq-config-f.pkl    check the path is right 
and pkl is download from https://github.com/NVlabs/stylegan2   https://drive.google.com/drive/folders/1yanUI9m4b4PWzR0eurKNq6JR1Bbfbh6L

the error is :
Traceback (most recent call last):
  File "/media/31_sdf/stylegan2/convert_weight.py", line 227, in <module>
    generator, discriminator, g_ema = pickle.load(f)
  File "/usr/local/lib/python3.6/dist-packages/dnnlib/tflib/network.py", line 279, in __setstate__
    assert state["version"] in [2, 3]

**Comment by rosinality** [comment]
I think maybe version of the code that created pickle is different from repository you set.

**Comment by nanlliu** [comment]
same issue here. i trained a model based off the original stylegan2 repo.

**Comment by lijiae** [comment]
I made the same mistake
delete it...it works momently : )

**Comment by MarkZXZX** [comment]
> I made the same mistake delete it...it works momently : )

Hi，I meet same problem, I wanna ask which one I should delete?
thanks

**Comment by MarkZXZX** [comment]
Maybe I found this solution!

the usage of "--repo stylegan2" is using the dnnlib in stylegan2, maybe u have installed the dnnlib by pip, so u should uninstall and try again
