### ISSUE TITLE
Some questions about fine-tuning model

### ISSUE THREAD

**Issue by honor3568** [rosinality/stylegan2-pytorch#213]
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for to_rgb1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgb1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.0.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.0.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.2.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.2.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.3.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.4.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 12, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for to_rgb1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgb1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.0.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.0.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.2.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.2.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.3.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.4.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 12, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for to_rgb1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgb1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.0.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.0.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.2.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.2.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.3.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.4.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 12, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
Traceback (most recent call last):
  File "train.py", line 418, in <module>
    generator.load_state_dict(ckpt["g"], strict=False)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for to_rgb1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgb1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.0.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.0.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.1.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.1.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.2.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.2.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.3.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.3.conv.weight: copying a param with shape torch.Size([1, 12, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 512, 1, 1]).
        size mismatch for to_rgbs.4.bias: copying a param with shape torch.Size([1, 12, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 1, 1]).
        size mismatch for to_rgbs.4.conv.weight: copying a param with shape torch.Size([1, 12, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1, 3, 256, 1, 1]).
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/bin/python', '-u', 'train.py', '--local_rank=3', '--batch', '16', 'dataset', '--ckpt', 'checkpoint/100000.pt']' returned non-zero exit status 1.
How can I deal with these questions?

**Comment by rosinality** [comment]
I think you used swagan checkpoints for stylegan2.
