### ISSUE TITLE
subprocess.CalledProcessError: Command '[××]' died with <Signals.SIGSEGV: 11>.

### ISSUE THREAD

**Issue by zju-lyf** [rosinality/stylegan2-pytorch#233]
Traceback (most recent call last):
  File "/public/home/anaconda3/envs/stylegan/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/public/home/anaconda3/envs/stylegan/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/public/home/anaconda3/envs/stylegan/lib/python3.6/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/public/home/anaconda3/envs/stylegan/lib/python3.6/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/public/home/anaconda3/envs/stylegan/bin/python', '-u', 'train.py', '--local_rank=1', '--batch', '16', './data/']' died with <Signals.SIGSEGV: 11>.

**Comment by MationPlays** [comment]
I have the same/similar issue: subprocess.CalledProcessError: Command '['C:\\Users\\USERNAME\\anaconda3\\envs\\stylegan-rosinality\\python.exe', '-u', 'train.py', '--local_rank=0', '--batch', '5', 'C:\\Users\\USERNAME\\LMBD_PATH']' returned non-zero exit status 1.
