### ISSUE TITLE
Error on running train.py

### ISSUE THREAD

**Issue by alexpollack** [rosinality/stylegan2-pytorch#24]
Hello,

I've been trying to get the training script to run but have been running into some issues. The current issue I'm facing seems to be somewhat similar to another post by _cyrilzakka_ from this week. when running `!python -m torch.distributed.launch --nproc_per_node=1 --master_port=1234 /content/stylegan2-pytorch/train.py --batch 5 /content/`, however his fix of changing the size of the batch doesn't seem to solve my issue. The bulk of the error message I receive is very similar to their, noting similar lines and faults, however also stating that there is a missing file for the 'op/fused_bias_act.cpp', even though the repo has been cloned. The error is:

 Traceback (most recent call last):
  File "/content/stylegan2-pytorch/train.py", line 21, in <module>
    from model import Generator, Discriminator
  File "/content/stylegan2-pytorch/model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/content/stylegan2-pytorch/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/content/stylegan2-pytorch/op/fused_act.py", line 6, in <module>
    fused = load('fused', sources=['op/fused_bias_act.cpp', 'op/fused_bias_act_kernel.cu'])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 809, in _jit_compile
    with_cuda=with_cuda
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 44, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 16, in hash_source_files
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'op/fused_bias_act.cpp'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', '/content/stylegan2-pytorch/train.py', '--local_rank=0', '--batch', '5', '/content/']' returned non-zero exit status 1.

**Comment by pc4653** [comment]
I'd check your cuda version to see if its 10.0+ in order to compile the custom ops from nvidia

**Comment by alexpollack** [comment]
I believe my environment should be up to date with what the README had required, currently running:
torch 1.3.1
torchvision 0.4.2
CUDA 10.1.168

**Comment by cyrilzakka** [comment]
are you running things on a single GPU by any chance (e.g. Colab)? If so your run command should look more like `!python train.py --batch 32 /content/ ` without the distributed training part.

**Comment by alexpollack** [comment]
I've tried both locally and on colab and seemed to get the same errors. After changing that realizing it should be set for only a single GPU a portion of the error is now gone, however it still seems to throw a fit about 'FileNotFound':

Traceback (most recent call last):
  File "/content/stylegan2-pytorch/train.py", line 21, in <module>
    from model import Generator, Discriminator
  File "/content/stylegan2-pytorch/model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/content/stylegan2-pytorch/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/content/stylegan2-pytorch/op/fused_act.py", line 6, in <module>
    fused = load('fused', sources=['op/fused_bias_act.cpp', 'op/fused_bias_act_kernel.cu'])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py", line 809, in _jit_compile
    with_cuda=with_cuda
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 44, in bump_version_if_changed
    hash_value = hash_source_files(hash_value, source_files)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/_cpp_extension_versioner.py", line 16, in hash_source_files
    with open(filename) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'op/fused_bias_act.cpp'

**Comment by cyrilzakka** [comment]
Next thing I’d try is running the training command after cd-ing into the StyleGAN repo. My guess is that should fix your error. If not, I’ll help you debug tomorrow after my exam

**Comment by alexpollack** [comment]
After cd-ing into the directory and trying to run directly from there, it seems as though it's almost working! Thank you!

I believe the train.py script to be running, however I still get an error, but this time relevant to the images. I'll take a further look into it but perhaps I'm doing something in the data preparation incorrect.
New fun error:
0% 0/800000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 434, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 179, in train
    real_img = next(loader)
  File "train.py", line 58, in sample_data
    for batch in loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/stylegan2-pytorch/dataset.py", line 37, in __getitem__
    img = Image.open(buffer)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7fafedf8cca8>

**Comment by cyrilzakka** [comment]
This error is the same as the one mentioned in issue #22. A temporary fix is to switch your image size to 256 in prepare_dataset.py for now until support for multiple image sizes is added.

**Comment by rosinality** [comment]
@alexpollack @cyrilzakka You will need to set --size arguments if you use image sizes different to 256px.

**Comment by cyrilzakka** [comment]
@rosinality works like a charm

**Comment by alexpollack** [comment]
Beautiful! Does work like a charm, thank you both @rosinality @cyrilzakka. And thank you again @rosinality especially for this great tool.
