### ISSUE TITLE
size argument for train.py throws error

### ISSUE THREAD

**Issue by DIMPLY** [rosinality/stylegan2-pytorch#253]
I'm using a dataset with size different from 256px.
After preparing the dataset, I ran `# python3 train.py --batch 150 --size 150 ./prepared_img`.
However, whatever value I set to --size, whether it's 150, 110, or 128, I always got:
```
Traceback (most recent call last):
  File "train.py", line 456, in <module>
    args.size, channel_multiplier=args.channel_multiplier
  File "/content/stylegan2-pytorch/model.py", line 655, in __init__
    convs = [ConvLayer(3, channels[size], 1)]
KeyError: 150
```
According to @alexpollack @cyrilzakka You will need to set --size arguments if you use image sizes different to 256px.

_Originally posted by @rosinality in https://github.com/rosinality/stylegan2-pytorch/issues/24#issuecomment-573313937_

Setting --size to a number different than 256 should have worked.

**Comment by DIMPLY** [comment]
Ah, I forgot to close this question. Actually, using one of 128, 256, 512, ..., etc. works, and no other sizes are allowed.
