### ISSUE TITLE
Error on loading checkpoint when training

### ISSUE THREAD

**Issue by cyrilzakka** [rosinality/stylegan2-pytorch#26]
Loading a model checkpoint results in the following error:

```
load model: /content/stylegan2-pytorch/checkpoint/010000.pt
Traceback (most recent call last):
  File "train.py", line 393, in <module>
    generator.load_state_dict(ckpt['g'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "convs.2.conv.weight", "convs.2.conv.blur.kernel", "convs.2.conv.modulation.weight", "convs.2.conv.modulation.bias", "convs.2.noise.weight", "convs.2.activate.bias", "convs.3.conv.weight", "convs.3.conv.modulation.weight", "convs.3.conv.modulation.bias", "convs.3.noise.weight", "convs.3.activate.bias", "to_rgbs.1.bias", "to_rgbs.1.upsample.kernel", "to_rgbs.1.conv.weight", "to_rgbs.1.conv.modulation.weight", "to_rgbs.1.conv.modulation.bias".
```
I will debug and get back to you as soon as I find a workaround!

**Comment by rosinality** [comment]
I got it. I think you can use load_state_dict(strict=False).

**Comment by cyrilzakka** [comment]
I saw that and was wondering, if it ignores any key that doesn't match, then is it truly going to load the checkpoint? Or will it just fail silently? Testing it out now. Shouldn't take more than 3 hours I hope.

**Comment by rosinality** [comment]
As convolution layers for 16x16 scale doesn't exists in the checkpoints, strict=False will only load layers until 8x8 instead.

**Comment by cyrilzakka** [comment]
Got a new error:
```
raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
```

**Comment by rosinality** [comment]
I think you can skip loading state dict of optimizers.

**Comment by cyrilzakka** [comment]
Can confirm everything now works fine. Modifying the following lines in `train.py` as so fixes the issues mentioned. Shall I submit a pull request or are you working on automating progressive training?

```
        generator.load_state_dict(ckpt['g'], strict=False)
        discriminator.load_state_dict(ckpt['d'], strict=False)
        g_ema.load_state_dict(ckpt['g_ema'], strict=False)

        #g_optim.load_state_dict(ckpt['g_optim'])
        #d_optim.load_state_dict(ckpt['d_optim'])
```

**Comment by rosinality** [comment]
As this implementation is not very adequate for progressive training, I think it will be not very appropriate to have options for that cases.
