### ISSUE TITLE
no module named 'dnnlib'

### ISSUE THREAD

**Issue by gzhhhere** [rosinality/stylegan2-pytorch#268]
![image](https://user-images.githubusercontent.com/43848061/142592652-c3790725-272e-4492-a5ae-7cbe93b95409.png)
![image](https://user-images.githubusercontent.com/43848061/142592717-c4dc4e44-1582-43f5-aeca-1921ae7dc12e.png)
i try to 'pip install dnnlib' but failed.
what should i do QAQ.

**Comment by gzhhhere** [comment]
oh, maybe i should install tensorflow

**Comment by gzhhhere** [comment]
installed tensorflow 2.6.0, still no module  named dnnlib.

**Comment by gzhhhere** [comment]
i saw 'You need to clone official repositories, (https://github.com/NVlabs/stylegan2) as it is requires for load official checkpoints.'

**Comment by gzhhhere** [comment]
i used docker by 'docker pull nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04' and ' pip3 install tensorflow-gpu==1.14.0 scipy==1.3.3 requests==2.22.0 Pillow==6.2.1 h5py==2.9.0 imageio==2.9.0 imageio-ffmpeg==0.4.2 tqdm==4.49.0 torch==1.4.0 torchvision==0.5.0 pandas numpy pillow==6.2.1 opencv-python scikit-learn matplotlib seaborn jupyterlab ninja'
but when i try to run convert_weight.py' i got '
Traceback (most recent call last):
  File "convert_weight.py", line 236, in <module>
    generator, discriminator, g_ema = pickle.load(f)
ModuleNotFoundError: No module named 'torch_utils''

**Comment by rosinality** [comment]
I think you have used checkpoints from stylegan2-ada-pytorch. Currently `convert_weight.py` does not support pytorch version of checkpoints.

**Comment by gzhhhere** [comment]
> 
Thanks for your attention,
what i try to convert is the 'stylegan2-celebahq-256x256.pkl' which is downloaded from https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files.

By the way 
![image](https://user-images.githubusercontent.com/43848061/142717266-63c5eb2a-14ad-4fea-b922-46c19a321969.png)
is the file structure right?
 i put your  repositories in stylegan2 repositories, 
and i cd into your repositories 
and put the .pkl in your  repositories
 then run 'python convert_weight.py --repo  /home/....../stylegan2  stylegan2-celebahq-256x256.pkl'

**Comment by gzhhhere** [comment]
> 
Thanks for your attention,
what i try to convert is the 'stylegan2-celebahq-256x256.pkl' which is downloaded from https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files.

By the way 
![image](https://user-images.githubusercontent.com/43848061/142717266-63c5eb2a-14ad-4fea-b922-46c19a321969.png)
is the file structure right?
 i put your  repositories in stylegan2 repositories, 
and i cd into your repositories 
and put the .pkl in your  repositories
 then run 'python convert_weight.py --repo  /home/....../stylegan2  stylegan2-celebahq-256x256.pkl'

**Comment by rosinality** [comment]
Yes, it is right.

**Comment by gzhhhere** [comment]
> Yes, it is right.
when i try to convert 'stylegan2-celebahq-256x256.pkl' 
i have 
' File "convert_weight.py", line 236, in <module>
    generator, discriminator, g_ema = pickle.load(f)
ModuleNotFoundError: No module named 'torch_utils'
when i try to conver 'stylegan2-ffhq-1024x1024.pkl'
i have 
Traceback (most recent call last):
  File "convert_weight.py", line 230, in <module>
    import dnnlib
ModuleNotFoundError: No module named 'dnnlib'

they are all download from https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files.

i think they are not ada weight, there should be some 'directories error'....

**Comment by gzhhhere** [comment]
> Yes, it is right.

when i try to convert 'stylegan2-celebahq-256x256.pkl'
i have
' File "convert_weight.py", line 236, in 
generator, discriminator, g_ema = pickle.load(f)
ModuleNotFoundError: No module named 'torch_utils'
when i try to conver 'stylegan2-ffhq-1024x1024.pkl'
i have
Traceback (most recent call last):
File "convert_weight.py", line 230, in 
import dnnlib
ModuleNotFoundError: No module named 'dnnlib'

they are all download from https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files.

i think they are not ada weight, there should be some 'directories error'....

**Comment by rosinality** [comment]
It seems like that it is from stylegan3. Currently it is not supported.

**Comment by gzhhhere** [comment]
> It seems like that it is for stylegan3. Currently it is not supported.

you are right, the weight from https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/ is converable using your code, however, i still can't get the ''stylegan2-celebahq.pt''.  Thanks for your attention again!

**Comment by alinacccc** [comment]
Have u solved this problem? I also encounterred this problem,and
i download the code of stylegan2 from github named stylegan2-pytorch-master,have u use this one?

**Comment by 49xxy** [comment]
> 我认为您使用了 stylegan2-ada-pytorch 中的检查点。目前`convert_weight.py`不支持 pytorch 版本的检查点。

Can you support it now，please?

**Comment by cavalier501** [comment]
[](https://github.com/podgorskiy/dnnlib)
this may help

**Comment by cavalier501** [comment]
[https://github.com/podgorskiy/dnnlib](https://github.com/podgorskiy/dnnlib)
this may help

**Comment by gmindflow** [comment]
This solved the issue, not getting it anymore. Thanks!

**Comment by zimenglan-sysu-512** [comment]
hi @gmindflow 
how dit u solve it?

**Comment by gmindflow** [comment]
It's been a while since a I met this issue 2months ago so can't remember exactly but I ran:
`pip install https://github.com/podgorskiy/dnnlib/releases/download/0.0.1/dnnlib-0.0.1-py3-none-any.whl`
and it solved the error that I was having at that time!

**Comment by maeri18** [comment]
> It's been a while since a I met this issue 2months ago so can't remember exactly but I ran: `pip install https://github.com/podgorskiy/dnnlib/releases/download/0.0.1/dnnlib-0.0.1-py3-none-any.whl` and it solved the error that I was having at that time!

It worked for me. Thankssss

**Comment by BCXNSD** [comment]
> It's been a while since a I met this issue 2months ago so can't remember exactly but I ran: `pip install https://github.com/podgorskiy/dnnlib/releases/download/0.0.1/dnnlib-0.0.1-py3-none-any.whl` and it solved the error that I was having at that time!

god bless you! 
you are so gorgeous!
