### ISSUE TITLE
Some keys are not found.

### ISSUE THREAD

**Issue by TiankaiHang** [rosinality/stylegan2-pytorch#274]
For `stylegan2-car-config-a.pkl`, 
```Traceback (most recent call last):
  File "convert_weight.py", line 248, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size, n_mlp)
  File "convert_weight.py", line 155, in fill_statedict
    update(state_dict, convert_torgb(vars, "G_synthesis/4x4/ToRGB", "to_rgb1"))
  File "convert_weight.py", line 61, in convert_torgb
    weight = vars[source_name + "/weight"].value().eval()```

**Comment by rosinality** [comment]
convert_weight.py and this repository does not support config-a.
