### ISSUE TITLE
Convert weight error

### ISSUE THREAD

**Issue by XYkong-CS** [rosinality/stylegan2-pytorch#281]
Thank you for your great project！
But i met some problems when i tried to convert the official tensorflow weight to your version.
I use the struction : 
CUDA_VISIBLE_DEVICES=2 python convert_weight.py --repo ../stylegan2 official_weight/stylegan2-church-config-a.pkl
and it is the weights of StyleGAN2 for LSUN Church dataset at 256×256.
But i got the following message:

Traceback (most recent call last):
  File "convert_weight.py", line 247, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size, n_mlp)
  File "convert_weight.py", line 154, in fill_statedict
    update(state_dict, convert_torgb(vars, "G_synthesis/4x4/ToRGB", "to_rgb1"))
  File "convert_weight.py", line 60, in convert_torgb
    weight = vars[source_name + "/weight"].value().eval()
KeyError: 'G_synthesis/4x4/ToRGB/weight'

How can i deal with it?
btw, do I need to specify the img_size of the weights or it can adapt itself?

**Comment by XYkong-CS** [comment]
I print he vars, but only "G_synthesis/ToRGB_lod0(/1/2/3/4/5/6)/weight" was found, instead of "G_synthesis/ToRGB/weight".
Do i use the wrong weight found on https://nvlabs-fi-cdn.nvidia.com/stylegan2/networks/ ?

**Comment by XYkong-CS** [comment]
It has been solved by using weight files with the suffix f !

**Comment by bsmhmmlf** [comment]
@kongxiuxiu have you got any 256*256 model for pytorch?

**Comment by XYkong-CS** [comment]
> @kongxiuxiu have you got any 256*256 model for pytorch?

Yes, and now I have converted 256*256 model for horse, cat and church

**Comment by bsmhmmlf** [comment]
@kongxiuxiu do they work well? the pics seem weird

**Comment by liushanyuan18** [comment]
> > @kongxiuxiu have you got any 256*256 model for pytorch?
> 
> Yes, and now I have converted 256*256 model for horse, cat and church

hi,could you please provide the three models?thank you so much!

**Comment by hhuyujie** [comment]
> > @kongxiuxiu have you got any 256*256 model for pytorch?
> 
> Yes, and now I have converted 256*256 model for horse, cat and church

Could you provide 256*256 pre-trained model for ffhq? Thank you very much!

**Comment by XYkong-CS** [comment]
> > > @kongxiuxiu have you got any 256*256 model for pytorch?
> > 
> > 
> > Yes, and now I have converted 256*256 model for horse, cat and church
> 
> hi,could you please provide the three models?thank you so much!

Sorry , I forgot my password and just found it back so I couldn't reply in time. Do you still need the weight files?

**Comment by XYkong-CS** [comment]
> > > @kongxiuxiu have you got any 256*256 model for pytorch?
> > 
> > 
> > Yes, and now I have converted 256*256 model for horse, cat and church
> 
> Could you provide 256*256 pre-trained model for ffhq? Thank you very much!

Sorry , I forgot my password and just found it back so I couldn't reply in time. Do you still need the weight files?

**Comment by hhuyujie** [comment]
您好，我已收到您的邮件。

**Comment by XYkong-CS** [comment]
> @kongxiuxiu do they work well? the pics seem weird

Most of them looks OK. It works much better than the model trained on my own.

**Comment by zengxianyu** [comment]
I converted all the 5 models for ffhq, horses, car, cats and church. They are probably correct as the generated images looks reasonable but I didn't check the result difference from tf models

https://maildluteducn-my.sharepoint.com/:u:/g/personal/zengyu_mail_dlut_edu_cn/EUoHD5628IxOjPb8jbWKSWsBoqOLUTsYeLXjXe9i5ahxvQ?e=Qs7SuX

**Comment by 49xxy** [comment]
> 

Is it possible to convert stylegan2-ada-PyTorch pkl model,please?

**Comment by hhuyujie** [comment]
您好，我已收到您的邮件。

**Comment by usmancheema89** [comment]
> > 
> 
> Is it possible to convert stylegan2-ada-PyTorch pkl model,please?

any luck with it ? :)
