### ISSUE TITLE
Time of converting

### ISSUE THREAD

**Issue by whyydsforever** [rosinality/stylegan2-pytorch#293]
I wonder how long it  takes to covert .pkl into .pt because after I run it, it did nothing for a long time?

**Comment by whyydsforever** [comment]
When I covert weights from .pkl to .pt It seems that it doesn't work and I use ctrl+c to end the process it turned out that the process was sleeping
(pytorch) PS D:\FYP\Labels4Free-main> python convert_weight.py --repo ~/pt stylegan2-cat-config-f.pkl
Traceback (most recent call last):
  File "convert_weight.py", line 11, in <module>
    from model_new import Generator, Discriminator
  File "D:\FYP\Labels4Free-main\model_new.py", line 12, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "D:\FYP\Labels4Free-main\op\__init__.py", line 2, in <module>
  File "D:\FYP\Labels4Free-main\op\upfirdn2d.py", line 10, in <module>
    upfirdn2d_op = load(
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1351, in _jit_compile
    baton.wait()
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt
(pytorch) PS D:\FYP\Labels4Free-main> python convert_weight.py --repo ~/pt stylegan2-cat-config-f.pkl
Traceback (most recent call last):
  File "convert_weight.py", line 11, in <module>
    from model_new import Generator, Discriminator
  File "D:\FYP\Labels4Free-main\model_new.py", line 12, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "D:\FYP\Labels4Free-main\op\__init__.py", line 2, in <module>
    from .upfirdn2d import upfirdn2d
  File "D:\FYP\Labels4Free-main\op\upfirdn2d.py", line 10, in <module>
    upfirdn2d_op = load(
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 1351, in _jit_compile
    baton.wait()
  File "C:\Users\wu\.conda\envs\pytorch\lib\site-packages\torch\utils\file_baton.py", line 42, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by wyiguanw** [comment]
hi, have you solved this issue? I run into same problem,

**Comment by tnb1021** [comment]
Me too. That didn't happen until last week, but this week I started having that problem.
