### ISSUE TITLE
Error train.py lmdb

### ISSUE THREAD

**Issue by tengolagan** [rosinality/stylegan2-pytorch#320]
Hi, I get this error while trying to train /

lmdb.Error: lmdb: No such file or directory 

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4800) of binary: /usr/local/bin/python Traceback (most recent call last):   
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec) 
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code     exec(code, run_globals)   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>     main()   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main     launch(args)   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch     run(args)   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/run.py", line 718, in run     )(*cmd_args)   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__     return launch_agent(self._config, self._entrypoint, list(args))   
File "/usr/local/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 247, in launch_agent     failures=result.failures, torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

Does anyone know how I should proceed to debug this ?

Thanks

**Comment by devzhk** [comment]
Can you first check your data path? "lmdb.Error: lmdb: No such file or directory", lmdb didn't find your file.
