### ISSUE TITLE
ffhq-e cannot be converted from official model but ffhq-f made it

### ISSUE THREAD

**Issue by XD666** [rosinality/stylegan2-pytorch#52]
```eGAN2_models/networks/stylegan2-ffhq-config-e.pkl
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
Traceback (most recent call last):
  File "convert_weight.py", line 214, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size)
  File "convert_weight.py", line 148, in fill_statedict
    convert_torgb(vars, f'G_synthesis/{reso}x{reso}/ToRGB', f'to_rgbs.{i}'),
  File "convert_weight.py", line 101, in update
    raise ValueError(f'Shape mismatch: {v.shape} vs {state_dict[k].shape}')
ValueError: Shape mismatch: torch.Size([1, 3, 256, 1, 1]) vs torch.Size([1, 3, 512, 1, 1])
`

**Comment by rosinality** [comment]
Added --channel_multiplier arguments to the convert_weight.py at c7c8fc7. Now you can use --channel_multiplier 1 options for converting config-e checkpoints.

**Comment by songyoyo** [comment]
@XD666 Hi, I'm also tring to convert the weight, but some errors ocurred. Can you share your implementation environment or the converted weight  file (ffhq-f)? My e-mail is 610240943@qq.com. THANK YOU VERY MUCH!

**Comment by woctezuma** [comment]
Similarly, it takes some time to check the code and understand that the script outputs an image with 3 rows:
- images generated with TensorFlow, PyTorch, and the difference between the two,

https://github.com/rosinality/stylegan2-pytorch/blob/d1ef862f3dac820a1d11b080f468269f735c1e8a/convert_weight.py#L273

![output image](https://i.imgur.com/Hfisg6H.jpg)

or that:
-   `--repo` is used to provide a path to the official StyleGAN2 repository with the `dnnlib/` folder,
-   `PATH` is the absolute path to the TensorFlow weights.
-   `--gen` is a boolean flag to convert the generator,
-   `--disc` is a boolean flag to convert the discriminator.

from:
```
usage: convert_weight.py [-h] --repo REPO [--gen] [--disc]
                         [--channel_multiplier CHANNEL_MULTIPLIER]
                         PATH

positional arguments:
  PATH

optional arguments:
  -h, --help            show this help message and exit
  --repo REPO
  --gen
  --disc
  --channel_multiplier CHANNEL_MULTIPLIER
```

**Comment by rosinality** [comment]
@woctezuma Yes...I will add some helps to command line arguments. I am quite lazy about that. 😅

**Comment by woctezuma** [comment]
I can understand that. It is not the most interesting part of the work. However, your converter tool does more things than I would have expected, so I think that providing a bit of clarity helps shine some light on the optional (yet useful) stuff that you did. :)

**Comment by rosinality** [comment]
@woctezuma Added cli argument helps at f938922c5ba7f9c325e5e13795da8ee93e849250.

**Comment by woctezuma** [comment]
Thank you very much! This will be super helpful!
