### ISSUE TITLE
Error when converting .pkl file to .pt 

### ISSUE THREAD

**Issue by fouratthamri** [rosinality/stylegan2-pytorch#65]
I trained a stylegan2-**config-e** model (from the official repo) on a custom dataset with size 256*256, but when I try to convert the weights to .pt with **convert_weight.py** I get this error :

```
Traceback (most recent call last):
  File "convert_weight.py", line 226, in <module>
    state_dict = fill_statedict(state_dict, g_ema.vars, size)
  File "convert_weight.py", line 192, in fill_statedict
    vars[f'G_synthesis/noise{i}'].value().eval()
  File "convert_weight.py", line 98, in update
    raise KeyError(k + ' is not found')
KeyError: 'noises.noise_0 is not found'
```

I don't know why the state_dict doesn't include this key ?

**Comment by rosinality** [comment]
Could you check model.py? https://github.com/rosinality/stylegan2-pytorch/blob/master/model.py#L424

**Comment by fouratthamri** [comment]
Thank you it works now, but consider updating the files of the models in the GanSpace repo, because the model.py in the that repo is different from the one that you sent me.
