### ISSUE TITLE
GPU error while loading checkpoint

### ISSUE THREAD

**Issue by krips89** [rosinality/stylegan2-pytorch#80]
While trying to resume training by loading a chekcpoint, I am getting the following error: 

`Traceback (most recent call 

> last):

  File "train.py", line 437, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 230, in train
    weighted_path_loss.backward()
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered
`

> Traceback (most recent call last):
  File "train.py", line 437, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 230, in train
    weighted_path_loss.backward()
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37/lib/python3.7/site-packages/torch/tensor.py", line 166, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by rosinality** [comment]
Could you try this? 27e6c99 I think it could be map_location related error.
